version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CURRENCY_API_KEY=${CURRENCY_API_KEY}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - BREVO_SENDER_EMAIL=${BREVO_SENDER_EMAIL}
      - BREVO_SENDER_NAME=${BREVO_SENDER_NAME}
      - GOOGLE_CALENDAR_ID=${GOOGLE_CALENDAR_ID}
      - GOOGLE_CALENDAR_CREDENTIALS_FILE=${GOOGLE_CALENDAR_CREDENTIALS_FILE}
    volumes:
      - ./src/main/resources:/app/resources 